#!/bin/bash
python3 recall_precision.py 10 their_webspam_cached2.txt my_webspam_cached2.txt 2 -save
python3 recall_precision.py 1 their_webspam_cached2.txt my_webspam_cached2.txt 2 -save
python3 recall_precision.py 10 their_url_cached2.txt my_url_cached2.txt 2 -save
python3 recall_precision.py 1 their_url_cached2.txt my_url_cached2.txt 2 -save

python3 recall_precision.py 10 their_webspam_cached2.txt my_webspam_cached2.txt 20 -save
python3 recall_precision.py 1 their_webspam_cached2.txt my_webspam_cached2.txt 20 -save
python3 recall_precision.py 10 their_url_cached2.txt my_url_cached2.txt 20 -save
python3 recall_precision.py 1 their_url_cached2.txt my_url_cached2.txt 20 -save

python3 recall_precision.py 10 their_webspam_cached2.txt my_webspam_cached2.txt 200 -save
python3 recall_precision.py 1 their_webspam_cached2.txt my_webspam_cached2.txt 200 -save
python3 recall_precision.py 10 their_url_cached2.txt my_url_cached2.txt 200 -save
python3 recall_precision.py 1 their_url_cached2.txt my_url_cached2.txt 200 -save